stages:
  preprocess:
    cmd: python src/preprocessing.py
    deps:
    - data/raw/heart.csv
    - src/preprocessing.py
    outs:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
